// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TheWell.Data;

#nullable disable

namespace TheWell.Data.Migrations
{
    [DbContext(typeof(WellDbContext))]
    partial class WellDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TheWell.Core.Entities.AuthenticationAudit", b =>
                {
                    b.Property<Guid>("AuditID").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("Action").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<DateTime>("AttemptTimestamp").HasColumnType("timestamp with time zone");
                    b.Property<DateTime?>("OtpExpiresAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("OtpHash").HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<Guid>("UserID").HasColumnType("uuid");
                    b.HasKey("AuditID");
                    b.HasIndex("UserID");
                    b.ToTable("AuthenticationAudits");
                });

            modelBuilder.Entity("TheWell.Core.Entities.CourseConfig", b =>
                {
                    b.Property<Guid>("ConfigID").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateOnly>("CourseEndDate").HasColumnType("date");
                    b.Property<DateOnly>("CourseStartDate").HasColumnType("date");
                    b.Property<DateTime>("SetAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("SetByAdminID").HasColumnType("uuid");
                    b.HasKey("ConfigID");
                    b.ToTable("CourseConfigs");
                });

            modelBuilder.Entity("TheWell.Core.Entities.DailyLog", b =>
                {
                    b.Property<Guid>("LogID").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<bool>("IsCompleted").HasColumnType("boolean");
                    b.Property<bool>("IsLocked").HasColumnType("boolean");
                    b.Property<DateOnly>("LogDate").HasColumnType("date");
                    b.Property<string>("Note").HasColumnType("text");
                    b.Property<Guid>("UserID").HasColumnType("uuid");
                    b.HasKey("LogID");
                    b.HasIndex("UserID", "LogDate").IsUnique();
                    b.ToTable("DailyLogs");
                });

            modelBuilder.Entity("TheWell.Core.Entities.Goal", b =>
                {
                    b.Property<Guid>("GoalID").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("GoalDefinition").IsRequired().HasColumnType("text");
                    b.Property<DateTime>("LockedAt").HasColumnType("timestamp with time zone");
                    b.Property<Guid>("UserID").HasColumnType("uuid");
                    b.HasKey("GoalID");
                    b.HasIndex("UserID").IsUnique();
                    b.ToTable("Goals");
                });

            modelBuilder.Entity("TheWell.Core.Entities.IntakeQuestion", b =>
                {
                    b.Property<Guid>("UserID").HasColumnType("uuid");
                    b.Property<DateTime?>("CompletedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("IAmPersonWho").IsRequired().HasColumnType("text");
                    b.Property<bool>("IsUnlocked").HasColumnType("boolean");
                    b.Property<string>("MyGoal").IsRequired().HasColumnType("text");
                    b.Property<string>("MyHabit").IsRequired().HasColumnType("text");
                    b.Property<string>("PeopleForEncouragement").IsRequired().HasColumnType("text");
                    b.Property<string>("RewardMyselfWith").IsRequired().HasColumnType("text");
                    b.Property<string>("Strategy1").IsRequired().HasColumnType("text");
                    b.Property<string>("Strategy2").IsRequired().HasColumnType("text");
                    b.Property<string>("ToImproveMyselfIWill").IsRequired().HasColumnType("text");
                    b.HasKey("UserID");
                    b.ToTable("IntakeQuestions");
                });

            modelBuilder.Entity("TheWell.Core.Entities.MetadataCache", b =>
                {
                    b.Property<Guid>("CacheID").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("ContentType").IsRequired().HasMaxLength(50).HasColumnType("character varying(50)");
                    b.Property<DateTime>("ExpiryDate").HasColumnType("timestamp with time zone");
                    b.Property<string>("Payload").IsRequired().HasColumnType("text");
                    b.HasKey("CacheID");
                    b.HasIndex("ContentType");
                    b.ToTable("MetadataCache");
                });

            modelBuilder.Entity("TheWell.Core.Entities.User", b =>
                {
                    b.Property<Guid>("UserID").ValueGeneratedOnAdd().HasColumnType("uuid");
                    b.Property<string>("AccountStatus").IsRequired().HasMaxLength(20).HasColumnType("character varying(20)");
                    b.Property<DateTime>("CreatedAt").HasColumnType("timestamp with time zone");
                    b.Property<string>("Email").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<bool>("IsPasswordResetRequired").HasColumnType("boolean");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(255).HasColumnType("character varying(255)");
                    b.Property<Guid?>("ProvisionedBy").HasColumnType("uuid");
                    b.Property<string>("UniversityEID").IsRequired().HasMaxLength(500).HasColumnType("character varying(500)");
                    b.Property<string>("UniversityEIDHash").IsRequired().HasMaxLength(64).HasColumnType("character varying(64)");
                    b.HasKey("UserID");
                    b.HasIndex("UniversityEID").IsUnique();
                    b.HasIndex("UniversityEIDHash");
                    b.ToTable("Users");
                });

            modelBuilder.Entity("TheWell.Core.Entities.AuthenticationAudit", b =>
                {
                    b.HasOne("TheWell.Core.Entities.User", "User")
                        .WithMany("AuthAudits").HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("TheWell.Core.Entities.DailyLog", b =>
                {
                    b.HasOne("TheWell.Core.Entities.User", "User")
                        .WithMany("DailyLogs").HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("TheWell.Core.Entities.Goal", b =>
                {
                    b.HasOne("TheWell.Core.Entities.User", "User")
                        .WithOne("Goal").HasForeignKey("TheWell.Core.Entities.Goal", "UserID")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("TheWell.Core.Entities.IntakeQuestion", b =>
                {
                    b.HasOne("TheWell.Core.Entities.User", "User")
                        .WithOne("IntakeQuestion").HasForeignKey("TheWell.Core.Entities.IntakeQuestion", "UserID")
                        .OnDelete(DeleteBehavior.Cascade).IsRequired();
                    b.Navigation("User");
                });

            modelBuilder.Entity("TheWell.Core.Entities.User", b =>
                {
                    b.Navigation("AuthAudits");
                    b.Navigation("DailyLogs");
                    b.Navigation("Goal");
                    b.Navigation("IntakeQuestion");
                });
#pragma warning restore 612, 618
        }
    }
}
